### ISSUE TITLE
relation to nested field not working

### ISSUE THREAD

**Issue by frankbits** [sveltia/sveltia-cms#13]
This field works in decapCMS:
```
- { name: "section", label: "Section", widget: relation, collection: "pages", value_field: "sections.*.id", display_fields: ["route", "sections.*.id"], search_fields: ["sections.*.id"] }
```
in sveltiaCMS nested fields can not be accessed.

DecapCMS-Doc:
> `value_field`: (required) name of the field from the referenced collection whose value will be stored for the relation. For nested fields, separate each subfield with a `.` (e.g. `name.first`). For list fields use a wildcard `*` to target all list items (e.g. categories.*).

would be nice to have this feature a documented (also not listed as missing in README.md)
- [ ] accessing nested fields
- [ ] `*`-wildcard for lists (also if `types`)
- [ ] save multiple fields of related collection? (_not in decapCMS_)

**Comment by kyoshino** [comment]
I thought I mentioned in README that wildcard matching is not supported yet. 😅 Well, the implementation is probably not so difficult — I’ll check it out this weekend.

**Comment by frankbits** [comment]
not as far a i can see 🤔 ...
and nested fields without wildcard is also not working

but yeah, thanks, gonna wit for that. 😀 
I really like these fast reactions to issues 😄

**Comment by kyoshino** [comment]
Sorry for the delay, the implementation is done!

> save multiple fields of related collection? (_not in decapCMS_)

I’ll defer it to another time. Basically, this may introduce the new `value_fields` (plural) property and save the value in an array, but things will be more complicated because the Relation widget already has the `multiple` option, and finding the referenced entry can perhaps be problematic.

Anyway, with this fix, nested fields, wildcards, and file collection list field referencing should all be supported. ✌🏻

**Comment by kyoshino** [comment]
And I just deployed the fix to production as v0.3.5 🚢

**Comment by frankbits** [comment]
Thanks!🙃

I think the README probably has to also be updated...🤔

**Comment by kyoshino** [comment]
I just updated 👍🏻
