### ISSUE TITLE
Correction for Local Development

### ISSUE THREAD

**Issue by syzio** [sveltia/sveltia-cms#195]
Hey, can't wait for 1.0

In the mean time, I would like to point out that the check for **Local Backend** at https://github.com/sveltia/sveltia-cms/blob/main/src/lib/components/entrance/sign-in.svelte#L24
while correct, could use clarification in the message and/or readme - that File System Access API is available since Chrome [86](https://developer.chrome.com/docs/capabilities/web-apis/file-system-access#browser_support), but some browsers, like Brave (what I use) require it to be enabled via a flag:
![image](https://github.com/user-attachments/assets/f4ecb5f3-ba5c-4756-9551-d8f467a7aed3)

**Comment by kyoshino** [comment]
It’s actually mentioned in the [README](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#working-with-a-local-git-repository). I’ll check if I can add Brave-specific message to the entrance page.

**Comment by syzio** [comment]
yeah that info is there, i was thinking just more like -
` 'showDirectoryPicker' in window || ( chrome > 86 && 'enable file system api')`

**Comment by kyoshino** [comment]
A message added in [v0.38.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.38.2).

Since we don’t know if all the chromium-based browsers support the File System Access API, and the way to enable it may vary by browser, it’s safe to show a message just to Brave users.

Anyway, thanks for the heads-up!
