### ISSUE TITLE
_index.md files can be created but not recognized by folder collections

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#206]
I saw the note in the readme, but I find this a bug. 
US: As a hugo editor, I want to use the same form to edit all of my section _index.md list pages.
Workaround: I can make a files collection that edits a files collection's files field, adding a new file for each content/{{ slug }}/_index.md, and import the same fields to every file.

**Comment by kyoshino** [comment]
Yes, omitting `_index.md` is by design, not a bug, because the special index file usually has (very) different fields from other files, right?

I could think about a different approach though: implement a filename-based filter as suggested in https://github.com/decaporg/decap-cms/issues/1245, exclude `_index.md` by default but allow developers to override the filter. WDYT?

**Comment by kyoshino** [comment]
Okay, so not extra config needed, but the CMS should respect `path` ending with `_index`. I’ll do it now.

**Comment by kyoshino** [comment]
[v0.39.12](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.12) fixed this issue, #207, and the checkbox bug mentioned in https://github.com/sveltia/sveltia-cms/issues/201#issuecomment-2352260882. Feel free to file new issues if you see any other bugs!
