### ISSUE TITLE
Quotes around Date strings break hugo sites

### ISSUE THREAD

**Issue by bmackinney** [sveltia/sveltia-cms#212]
Suggest not quotifying dateTime widget outputs. Possibly making "" a field option that can be set at the cms config level and per field.

**Comment by kyoshino** [comment]
String fields are not quoted unless required, e.g. an empty string. It’s automatically handled by the YAML library.

I don’t see quotes when saving `#/collections/hugo-content-default/entries/collections` with a date specified.

```yaml
date: 2024-09-29T05:17
```

but I do see a Hugo error after saving the file:

```
invalid front matter: date: 2024-09-29T05:17
```

Not sure why Hugo doesn’t accept this, but my quick test finds adding seconds (`:00`) solves the issue. I can fix it now.

Hugo also crashes when saving the entry _without_ a date specified, but I have nothing to do with it because the field is not required and an empty string must be quoted.

**Comment by kyoshino** [comment]
> Not sure why Hugo doesn’t accept this, but my quick test finds adding seconds (`:00`) solves the issue. I can fix it now.

This is done in [v0.39.16](https://github.com/sveltia/sveltia-cms/releases/tag/v0.39.16).

> Hugo also crashes when saving the entry _without_ a date specified, but I have nothing to do with it because the field is not required and an empty string must be quoted.

So I’m closing the issue as unplanned. I think you can make the field required to work around the crash.
