### ISSUE TITLE
Getting int from json file not working properly

### ISSUE THREAD

**Issue by adriandpdev** [sveltia/sveltia-cms#282]
Good afternoon and Merry Christmas, first of all.

I was migrating to this cms and I have the following problem. I store all the information of the videos that are shown on the web in a json. The first field is an id that should be auto-generated, and should increase based on the new videos, but it does not pick it up correctly from the file.

![image](https://github.com/user-attachments/assets/758637ff-5726-4a1f-b0ca-304ffc6a3b67)
![image](https://github.com/user-attachments/assets/37d695fc-031f-4c44-a90c-f74a1744848e)
![image](https://github.com/user-attachments/assets/126b09c5-af8b-4889-abd9-1314f5106d23)

https://www.alineacionindebida.com/videos 

Bonus: When you save the file, it writes a new line at the end, which, due to good practices, json files should not have (as indicated by eslint).

**Comment by kyoshino** [comment]
Fixed with [v0.49.8](https://github.com/sveltia/sveltia-cms/releases/tag/v0.49.8) 🙇🏼 You should be able to see the numbers after reloading the CMS.

> Bonus: When you save the file, it writes a new line at the end, which, due to good practices, json files should not have (as indicated by eslint).

I guess that’s not a typical ESLint (or Prettier?) setting. The new line is intentionally added because some text editors add it automatically and Git commits should not be screwed up with such changes. It’s a solution for https://github.com/decaporg/decap-cms/issues/1382 and part of [better data output](https://github.com/sveltia/sveltia-cms?tab=readme-ov-file#better-data-output) in Sveltia CMS.

**Comment by adriandpdev** [comment]
Works perfect! thanks!!

End line not problem
