### ISSUE TITLE
Allow for local development in other browsers: Firefox

### ISSUE THREAD

**Issue by noodles4u** [sveltia/sveltia-cms#38]
Hello, it seems like local development is only enabled in Chrome or Edge.

Not all chromium browsers are supported though, I cannot access the admin panel in Brave.

Would it be possible to include Firefox?

**Comment by kyoshino** [comment]
As a former employee/contractor/volunteer for Mozilla, I’d like to support Firefox for sure! My primary browser is Firefox. Unfortunately, it’s not possible because Mozilla has decided [not to support](https://github.com/WebKit/standards-positions/issues/28) the File System Access API (local file access) in Firefox. 😿 

I haven’t tested with Brave; will update README to remove “other Chromium-based desktop browser.”

**Comment by w0rldart** [comment]
It seems that File Systems API can be enabled for Brave via `chrome://flags/#file-system-access-api` or `brave://flags/#file-system-access-api`

**Comment by kyoshino** [comment]
Thanks! I haven’t tested myself but added a note to [README](https://github.com/sveltia/sveltia-cms#work-with-a-local-git-repository).

**Comment by kyoshino** [comment]
Just pinged by @Greenheart in #838 and realized that Mozilla now [plans to implement the API](https://bugzilla.mozilla.org/show_bug.cgi?id=1909237) in Firefox. I’ll reopen the issue to track the progress.

Aside from the [documentation](https://sveltiacms.app/en/docs/workflows/local), I don’t think we need to do any additional work on our end. It should work once Firefox implements it.
